services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: employee-tracker
    container_name: employee-tracker-container
    ports:
      - "7000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__ProductDbContext=Server=host.docker.internal,1433;Database=EmployeeTracker;User Id=sa;Password=Pa$$w0rd;TrustServerCertificate=true
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
