version: "3.8"

services:
  employeemanager-employee:
    image: employeemanager-employee
    container_name: employeemanager-employee-container
    build:
      context: ./EmployeeManager
      dockerfile: Dockerfile
    ports:
      - "9080:8080"
      - "9081:8081"
    environment:
      - DOTNET_ENVIRONMENT=Production
    networks:
      - my_network

  employeemanager-identity:
    image: employeemanager-identity
    container_name: employeemanager-identity-container
    build:
      context: ./Identity
      dockerfile: Dockerfile
    ports:
      - "9090:8080"
      - "9091:8081"
    environment:
      - DOTNET_ENVIRONMENT=Production
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
