version: "3.8"

services:
  employeemanager-employee:
    image: employeemanager-employee
    container_name: employeemanager-employee-container
    build:
      context: ./EmployeeManager
      dockerfile: Dockerfile
    ports:
      - "5040:5040"
      - "5041:5041"
      - "9040:9040"
      - "9041:9041"
    environment:
      - DOTNET_ENVIRONMENT=Production
    networks:
      - my_network

  employeemanager-identity:
    image: employeemanager-identity
    container_name: employeemanager-identity-container
    build:
      context: ./Identity
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
      - "5051:5051"
      - "9050:9050"
      - "9051:9051"
    environment:
      - DOTNET_ENVIRONMENT=Production
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
