@EmployeeTracker.Web_HostAddress = https://localhost:7029

POST {{EmployeeTracker.Web_HostAddress}}/api/v1/sessions
Content-Type: application/json

{
  "email": "admin@example.com",
  "passwordRaw": "Pa$$w0rd"
}

###
